# Generated by Django 4.1 on 2022-08-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductDesctiption', models.TextField()),
                ('PRICE', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerEmail', models.EmailField(max_length=100)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.producttable')),
            ],
        ),
    ]
